// Generated by Wrangler by running `wrangler types`

interface Env {
	stripe_public: "pk_test_51QuyeADExxj7eQXoLPDzEb1iogWsRnUZfr73H0pVfXtyU4GWyRY7e6ctAJR8NP1gc3ggj63adkm76xDqGYmxbQOM00EBLbKpyJ" | "pk_live_519kwRNDbPsEvuyro3rmyucNffyny87P6c972CRHGdpqrpK8SYrHvtVBAhbHjBzEc4wBKvDvBBKxQkeCv8FOnoZ0B00PWA89gOO";
	open: "2025-04-01T00:00:00.000-04:00";
	close: "2025-05-01T00:00:00.000-04:00";
	walk: "2025-05-23T13:00:00.000-04:00";
	seats: "100";
	combo: "88";
	event: "58";
	voucher: "53";
	shirt: "20";
	shirts: "20";
	shirtm: "20";
	shirtl: "20";
	shirtx: "20";
	shirtxx: "20";
	shirtxxx: "20";
	resend_key: string;
	stripe_secret: string;
	stripe_secret_live: string;
	DB: D1Database;
}
