name: build

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm clean-install
      - run: npm test
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: .sarif

  publish:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: ${{ (github.ref_name == 'main' && 'production') || 'preview' }}
      url: https://${{ (github.ref_name == 'main' && '') || github.ref_name }}${{ vars.HOST }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm clean-install
      - run: npx astro build
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy --project-name=hotdogwalk-com
